name: flownet2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cffi=1.14.0
  - cudatoolkit=10.0.130
  - freetype=2.9.1
  - imagesize=1.2.0
  - intel-openmp=2020.1
  - jpeg=9b
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1g
  - pillow=7.1.2
  - pip=20.0.2
  - pycparser=2.20
  - python=3.7.7
  - python_abi=3.7
  - pytorch=1.2.0
  - readline=8.0
  - setuptools=47.1.1
  - six=1.15.0
  - sqlite=3.31.1
  - tk=8.6.8
  - torchvision=0.4.0
  - tqdm=4.48.0
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - coloredlogs==14.0
    - cycler==0.10.0
    - humanfriendly==8.2
    - kiwisolver==1.2.0
    - matplotlib==3.2.1
    - opencv-python==4.2.0.34
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pyyaml==5.3.1

