name: poking
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - backcall=0.2.0
  - blas=1.0
  - blessings=1.7
  - ca-certificates=2020.6.20
  - cffi=1.14.0
  - cudatoolkit=10.2.89
  - cudnn=7.6.5
  - cupy=7.8.0
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.20.0
  - dbus=1.13.6
  - decorator=4.4.2
  - enum34=1.1.10
  - expat=2.2.9
  - fastrlock=0.5
  - fontconfig=2.13.1
  - freetype=2.9.1
  - glib=2.65.0
  - gpustat=0.6.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - ignite=0.4.1
  - imagecodecs-lite=2019.12.3
  - imageio=2.9.0
  - imagesize=1.2.0
  - intel-openmp=2020.1
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.1
  - joblib=0.16.0
  - jpeg=9b
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4-c=1.9.2
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - nccl=2.7.8.1
  - ncurses=6.2
  - networkx=2.4
  - ninja=1.9.0
  - nvidia-ml=7.352.0
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=1.1.1
  - parso=0.7.0
  - pathlib=1.0.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.0.2
  - prompt-toolkit=3.0.5
  - psutil=5.7.0
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.6.0
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - readline=8.0
  - scikit-image=0.16.2
  - scikit-learn=0.23.2
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.31.1
  - threadpoolctl=2.1.0
  - tifffile=2019.7.26.2
  - tk=8.6.8
  - toolz=0.10.0
  - torchvision=0.7.0
  - tornado=6.0.4
  - tqdm=4.47.0
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - absl-py==0.10.0
    - array2gif==1.0.4
    - astunparse==1.6.3
    - attrs==20.1.0
    - cachetools==4.1.1
    - certifi==2020.6.20
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.3.0
    - coloredlogs==14.0
    - configparser==5.0.0
    - dill==0.3.2
    - dm-tree==0.1.5
    - docker-pycreds==0.4.0
    - fsspec==0.8.2
    - future==0.18.2
    - gast==0.2.2
    - gitdb==4.0.5
    - gitpython==3.1.7
    - google-auth==1.20.1
    - google-auth-oauthlib==0.4.1
    - googleapis-common-protos==1.52.0
    - gql==0.2.0
    - graphql-core==1.1
    - grpcio==1.32.0
    - humanfriendly==8.2
    - idna==2.10
    - imageio-ffmpeg==0.4.2
    - importlib-metadata==1.7.0
    - imutils==0.5.3
    - kornia==0.4.0
    - llvmlite==0.34.0
    - lpips==0.1
    - markdown==3.2.2
    - moviepy==1.0.3
    - natsort==7.0.1
    - numba==0.51.1
    - numpy==1.19.1
    - oauthlib==3.1.0
    - opencv-python==4.2.0.34
    - opt-einsum==3.3.0
    - pathtools==0.1.2
    - proglog==0.1.9
    - promise==2.3
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytorch-lightning==0.9.1rc3
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scipy==1.5.2
    - sentry-sdk==0.16.1
    - setuptools==49.6.0
    - shortuuid==1.0.1
    - smmap==3.0.4
    - subprocess32==3.5.4
    - tensorboard==2.2.0
    - tensorboard-plugin-wit==1.7.0
    - termcolor==1.1.0
    - tfrecord==1.11
    - torchsummary==1.5.1
    - urllib3==1.25.10
    - wandb==0.9.3
    - watchdog==0.10.3
    - werkzeug==1.0.1
    - wheel==0.35.1
    - zipp==3.1.0
