name: poking
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.0.130
  - gpustat=0.6.0
  - ignite=0.4.1
  - imageio=2.9.0
  - imagesize=1.2.0
  - matplotlib=3.2.1
  - pillow=7.1.2
  - pip=20.0.2
  - python=3.7.7
  - pytorch=1.4.0
  - scikit-image=0.16.2
  - scikit-learn=0.23.2
  - torchvision=0.5.0
  - tqdm=4.47.0
  - yaml=0.2.5
  - pip:
    - absl-py==0.10.0
    - coloredlogs==14.0
    - h5py==2.10.0
    - imageio-ffmpeg==0.4.2
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - moviepy==1.0.3
    - natsort==7.0.1
    - numpy==1.19.1
    - opencv-python==4.2.0.34
    - opt-einsum==3.3.0
    - scipy==1.5.2
    - tensorboard==2.1.1
    - tensorboard-plugin-wit==1.7.0
    - tensorflow-datasets==3.2.1
    - tensorflow-estimator==2.1.0
    - tensorflow-gan==1.0.0.dev0
    - tensorflow-gpu==2.0.0
    - tensorflow-hub==0.6.0
    - tensorflow-metadata==0.23.0
    - tensorflow-probability==0.11.0
    - tfrecord==1.11
    - torchsummary==1.5.1
    - wandb==0.9.3
