raw_dir: '/export/scratch/compvis/datasets/plants/cropped_complete'
processed_dir: '/export/scratch/ablattma/datasets/plants'
rgb_max: 1.0
fp16_scale: 1024.0
flow_delta: 10
flow_max: 30
mode: all # should be in [all, extract, prepare]
video_format: mkv
spatial_size: 256
input_size: 1024
frames_discr: 1
target_gpus: 9
num_workers: 1
