raw_dir: '/export/scratch/compvis/datasets/plants/poking_plants'
processed_dir: '/export/scratch/ablattma/datasets/plants'
rgb_max: 1.0 # flownet2 parameter --> leave as is
fp16_scale: 1024.0 # flownet2 parameter --> leave as is
flow_max: 30 # maximum number of frames between which optical flow will be estimated
flow_delta: 10 # discretization step for optical flow estimates so for this example, we would have 3 flow maps per image pair where for frame 0, it would be flow_0-->10, flow_0-->20 and flow_0-->30
mode: stats # should be in [all, extract, prepare,stats, norms]
video_format: mkv
spatial_size: 256 # the output size of the images and flow maps
input_size: 1024 # the input size for the flow estimator i.e. the spatial resolution of the processed videos
frames_discr: 1
target_gpus: [0] # ids of the gpus, among which the processes will be devided
num_workers: 1 # number of parallel-working optical flow estimators to process the data


data:
  dataset: PlantDataset
  spatial_size: !!python/tuple [64,64]
  poke_size: 3
  n_pokes: 1
  # whether to split after videos or randomly (in a reproducible way)
  split: gui #official
  num_workers: 20
  excluded_objects: [] # for iper leave empty, for plants, use [8]
  # list containing the lags, curren6l, its indices are allowed to be within the intervall [0,5], otherwise, an error is throw
  # can be in [image, video]
  yield_videos: True
  # augmentation parameters for color transformations
  p_col: 0.8
  p_geom: 0.8
  augment_b: 0.4
  augment_c: 0.5
  augment_h: 0.15
  augment_s: 0.4
  # augmentation parameters for geometric transformations
  aug_deg: 15 # for iper use 0, for plants use 30°
  # translation is (vertical, horizontal)
  aug_trans: !!python/tuple [0.1,0.1] # for iper use [0.1,0.6], for plants use [0.1,0.1]
  # whether to get flow weight
  foreground_value: 10.
  background_weight: 1.
  # filter
  filter: all
  fancy_aug: False
  # whether to load flow/images in ram
  flow_in_ram: False
  imgs_in_ram: False
  # sequence parameters
  max_frames: 10
  augment_wo_dis: True
  equal_poke_val: True
  subsample_step: 2
  flow_weights: False
  n_ref_frames: 10